name: Generate index
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Update index
        run: node scripts/generate_index.mjs
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update index file
          file_pattern: index.json
